pic2text/urls.py
"""upload URL Configuration"""

from django.conf.urls import url
from . import views

urlpatterns = [  
	url(r'^$', views.upload, name='upload'),
	url(r'^return_text/$', views.return_text, name='return_text'),
]
app_name = 'pic2text'

upload/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'pic2text/', include('pic2text.urls', namespace='pic2text')),
]

pic2text/models.py
from django.db import models

# Create your models here.

pic2text/views.py
from django.shortcuts import render
from django.http import HttpResponse
import os
import configparser
from aip import AipOcr
from upload import settings

"""just test for git reset."""

def upload(request):
	return render(request, 'pic2text/upload.html')

def aip_client(work_order):
	target = configparser.ConfigParser()
	target.read(work_order)  
	APP_ID = target.get('pic2text', "AppID")
	API_KEY = target.get('pic2text', "API_Key")
	SECRET_KEY = target.get('pic2text', "Secret_Key")
	client = AipOcr(APP_ID, API_KEY, SECRET_KEY)
	return client

def get_text(client, image):
	result_dict = client.basicAccurate(image)
	text = ''
	words_result = result_dict.get("words_result")
	if words_result:
		for words_dict in words_result:
			text += words_dict.get('words', '') + '\r\n'
		return text

def return_text(request):
	work_order = os.path.join(settings.SOURCE_DIRS, 'baidu/character_recognition.ini')
	client = aip_client(work_order)
	pic = request.FILES.get("pic")
	if not pic:
		error = '未选择文件'
		return HttpResponse(error)
	filename = pic.name
	image = pic.read()
	text = get_text(client, image)
	if not text:
		error = '转换失败'
		return HttpResponse(error)
	context = {'filename':filename, 'text':text}
	return render(request, 'pic2text/result.html', context=context)

pic2text/templates/pic2text/result.html
<html>
	<head>
		<meta charset="utf-8" />
		<title>result</title>
	</head>
	<body>
		<p><a href="{% url 'pic2text:upload' %}" target="_parent">返回</a></p>
		<h5>{{ filename }}</h5>
		<textarea id="text" cols="160" rows="10" >
			{{ text }}
		</textarea>
		<p><button onclick="copy_text()">一键复制</button></p>
		<script>
			function copy_text(){
			var ele = document.getElementById("text");
			ele.select();
			document.execCommand("Copy");
			}
		</script>
	</body>
</html>

pic2text/templates/pic2text/upload.html
<html>
<head>
	<meta charset="utf-8" />
	<title>pic2text</title>
</head>
<body>
	<img src="/static/pic/logo.png" alt="logo" />
	<form action="{% url 'pic2text:return_text' %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<p><input type="file" name="pic"></p>
		<p><input type="submit" name="上传"></p>
	</form>
</body>
</html>